### ISSUE TITLE
Исправить опечатки в названиях переменных

### ISSUE THREAD

**Issue by coursar** [niyazic97/calculate-contribution-servis#2]
https://github.com/niyazic97/calculate-contribution-servis/blob/a6234c51329b05cbe0cd7c3b3f989ef93b0803c7/src/main/java/ru/itpark/service/CalculateContributionService.java#L4

**Comment by niyazic97** [comment]
@coursar Исправил.
https://github.com/niyazic97/calculate-contribution-servis/commit/f963a3ef8c66e10eba987d2678653e57ccf0115f
