### ISSUE TITLE
Для счётчиков циклов общеприняты три имени: i, j, k (i используется всегда, j и k - для вложенных циклов)

### ISSUE THREAD

**Issue by coursar** [niyazic97/calculate-contribution-servis#3]
https://github.com/niyazic97/calculate-contribution-servis/blob/a6234c51329b05cbe0cd7c3b3f989ef93b0803c7/src/main/java/ru/itpark/service/CalculateContributionService.java#L6

**Comment by niyazic97** [comment]
@coursar , Исправил
https://github.com/niyazic97/calculate-contribution-servis/commit/67b34f1367a1098d49eede291c49e5dee9b96fb7
