### ISSUE TITLE
Используйте '_' для визуального разделения разрядов

### ISSUE THREAD

**Issue by coursar** [niyazic97/calculate-contribution-servis#5]
https://github.com/niyazic97/calculate-contribution-servis/blob/a6234c51329b05cbe0cd7c3b3f989ef93b0803c7/src/test/java/ru/itpark/service/CalculateContributionServiceTest.java#L12-L13

**Comment by niyazic97** [comment]
@coursar 
Исправил
https://github.com/niyazic97/calculate-contribution-servis/commit/616ae641cbd8735e7b328b59ac13eaf59166f3a1
